### ISSUE TITLE
Bug in minimization

### ISSUE THREAD

**Issue by dzhu** [Garvys/rustfst#158]
I'm using the latest version of Rustfst from Git (1ddd1da6). [This file](https://github.com/Garvys/rustfst/files/6073062/bug.txt) contains an FST that appears to be turned into a non-equivalent FST by `minimize()`. The following test program should demonstrate the difference (save the linked file as `bug.txt`):

```rust
use rustfst::prelude::*;

fn main() {
    let path = fst_path![97, 98, 97, 100, 32];

    let mut fst: VectorFst<TropicalWeight> = VectorFst::read_text("bug.txt").unwrap();
    let accept1 = check_path_in_fst(&fst, &path);
    minimize(&mut fst).unwrap();
    let accept2 = check_path_in_fst(&fst, &path);

    assert_ne!(accept1, accept2);
}
```

The given path is rejected by the original FST but accepted by the minimized one.

I believe the issue arises because, in `AcyclicMinimizer::refine`, the partition is cloned into the comparator and used without being changed, while the original partition is updated as the function runs. As a result, two states with the same height that have the same number of transitions, where all the corresponding transitions have the same labels and point to states that were _originally_ in the same partition class (i.e., they have the same height) are merged, even if the pointed-to states have _since_ been distinguished and moved into different partition classes by earlier iterations of the loop.

Simply moving the declaration of `state_cmp` inside the loop (so that the comparator always has an up-to-date partition) gives correct behavior on my test case and still passes all of the existing test cases in the repo, which gives me some confidence that this idea is correct. Unfortunately, that does mean the clone happens even more times than before—I'm not sure if there's a good way to avoid that.

**Comment by dzhu** [comment]
I did some tinkering with the code and have put together some patches that I believe address the problem cleanly and even improve performance (after admittedly minimal benchmarking). I'll plan to open a PR soon.

**Comment by Garvys** [comment]
Hello ! Thanks for opening this issue ! Nice catch 👍
