### ISSUE TITLE
Python 3.11 support?

### ISSUE THREAD

**Issue by adampauls** [Garvys/rustfst#239]
PyPI says that 3.11 is supported, but I don't see any 3.11 versions in the [list of files](https://pypi.org/project/rustfst-python/#files). I can't install the latest version on my machine, but I'm not sure if the problem is the python version (3.11) or the MacOS version (13).

**Comment by Garvys** [comment]
Hey ! I just release version 0.13.3 of rustfst which ships wheels for python 3.11.

https://pypi.org/project/rustfst-python/0.13.3/

Tell me if that fixes your problem ! :-)

**Comment by sammthomson** [comment]
not sure if this is a conclusive datapoint, but I can confirm that rustfst-python 0.13.5 is working for me with Python 3.11.6 on Mac OS 14
