### ISSUE TITLE
Benchmarks or comparison with OpenFST?

### ISSUE THREAD

**Issue by daniel-emotech** [Garvys/rustfst#75]
Just wondering if there was any works to gauge the performance of rustfst with OpenFST?

**Comment by Garvys** [comment]
Hey !

Thanks for your interest in the project 🤗!

I did a benchmark some time ago on almost every linear fst algorithm and compared the results with `OpenFst`. You can find the results here : 
- Benchmark at the C++ level : https://github.com/Garvys/rustfst/blob/master/bench_results/bench_funct_80.md
- Benchmark at the CLI level : https://github.com/Garvys/rustfst/blob/master/bench_results/bench_cli_80.md

Spoiler alert: `rustfst` is faster on all those algorithms 😅 

For the other algorithms, i'm finishing the implementation then will do another round of benchmarks.

At the moment, the main algorithm missing in `rustfst` is the composition that will be implemented shortly. All the important algorithms like minimization, determinization ... are already implemented but not benched and thus not optimized.

This is ongoing work ! :) 

I'm more than open to PR if you want to contribute :-) 

Cheers

**Comment by daniel-emotech** [comment]
Awesome, I may contribute in future, I'll close this issue as it's answered my query :smile:

**Comment by Garvys** [comment]
Alright 👍

**Comment by MBkkt** [comment]
Hello, what are version of openfst used in benchmarks?

**Comment by MBkkt** [comment]
Think, I found https://github.com/Garvys/rustfst/blob/main/run_openfst.sh#L12
